"""laboratorio do medicamento

Revision ID: 7bba8873af7c
Revises: d62f8f213dff
Create Date: 2026-09-30 09:18:08.432468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bba8873af7c'
down_revision: Union[str, None] = 'd62f8f213dff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('laboratorio', sa.String(length=200), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicamentos', schema=None) as batch_op:
        batch_op.drop_column('laboratorio')

    # ### end Alembic commands ###
