"""esquema inicial

Revision ID: bfd82a063a33
Revises: 
Create Date: 2026-09-29 13:04:14.525466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfd82a063a33'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_consultas',
    sa.Column('chave', sa.String(length=300), nullable=False),
    sa.Column('valor', sa.JSON(), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('chave')
    )
    with op.batch_alter_table('cache_consultas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cache_consultas_expira_em'), ['expira_em'], unique=False)

    op.create_table('execucoes_tarefas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tarefa', sa.String(length=60), nullable=False),
    sa.Column('parametros', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resumo', sa.JSON(), nullable=False),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('iniciada_em', sa.DateTime(), nullable=False),
    sa.Column('terminada_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execucoes_tarefas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execucoes_tarefas_tarefa'), ['tarefa'], unique=False)

    op.create_table('medicamentos',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('principio_ativo', sa.Text(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('classe_terapeutica', sa.String(length=300), nullable=False),
    sa.Column('sinonimias', sa.JSON(), nullable=False),
    sa.Column('alternativas', sa.JSON(), nullable=False),
    sa.Column('preco_referencia', sa.Float(), nullable=True),
    sa.Column('so_hospitalar', sa.Boolean(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('redes',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('plataforma', sa.String(length=20), nullable=False),
    sa.Column('base_url', sa.String(length=200), nullable=True),
    sa.Column('coleta_ativa', sa.Boolean(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('trechos_nome', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos_cmed',
    sa.Column('ggrem', sa.String(length=20), nullable=False),
    sa.Column('medicamento_id', sa.String(length=160), nullable=False),
    sa.Column('registro', sa.String(length=20), nullable=False),
    sa.Column('ean1', sa.String(length=14), nullable=True),
    sa.Column('ean2', sa.String(length=14), nullable=True),
    sa.Column('ean3', sa.String(length=14), nullable=True),
    sa.Column('substancia', sa.Text(), nullable=False),
    sa.Column('produto', sa.String(length=200), nullable=False),
    sa.Column('laboratorio', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('apresentacao', sa.Text(), nullable=False),
    sa.Column('classe_terapeutica', sa.String(length=300), nullable=False),
    sa.Column('tipo_produto', sa.String(length=60), nullable=False),
    sa.Column('regime_preco', sa.String(length=30), nullable=False),
    sa.Column('tarja', sa.String(length=60), nullable=False),
    sa.Column('restricao_hospitalar', sa.Boolean(), nullable=False),
    sa.Column('pf_por_aliquota', sa.JSON(), nullable=False),
    sa.Column('pmc_por_aliquota', sa.JSON(), nullable=False),
    sa.Column('pmc_referencia', sa.Float(), nullable=True),
    sa.Column('chave_apresentacao', sa.String(length=120), nullable=True),
    sa.Column('lista_publicada_em', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamentos.id'], ),
    sa.PrimaryKeyConstraint('ggrem')
    )
    with op.batch_alter_table('produtos_cmed', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produtos_cmed_chave_apresentacao'), ['chave_apresentacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_cmed_ean1'), ['ean1'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_cmed_ean2'), ['ean2'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_cmed_ean3'), ['ean3'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_cmed_medicamento_id'), ['medicamento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_cmed_produto'), ['produto'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_cmed_registro'), ['registro'], unique=False)

    op.create_table('mapeamento_sku_redes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rede_id', sa.String(length=40), nullable=False),
    sa.Column('sku_rede', sa.String(length=300), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('ean', sa.String(length=14), nullable=True),
    sa.Column('registro', sa.String(length=20), nullable=True),
    sa.Column('produto_cmed_ggrem', sa.String(length=20), nullable=True),
    sa.Column('medicamento_id', sa.String(length=160), nullable=True),
    sa.Column('chave_apresentacao', sa.String(length=120), nullable=True),
    sa.Column('metodo_match', sa.String(length=20), nullable=False),
    sa.Column('score_match', sa.Float(), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('pbm', sa.JSON(), nullable=True),
    sa.Column('ultimo_preco', sa.Float(), nullable=True),
    sa.Column('ultimo_preco_em', sa.DateTime(), nullable=True),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamentos.id'], ),
    sa.ForeignKeyConstraint(['produto_cmed_ggrem'], ['produtos_cmed.ggrem'], ),
    sa.ForeignKeyConstraint(['rede_id'], ['redes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rede_id', 'sku_rede', name='uq_sku_por_rede')
    )
    with op.batch_alter_table('mapeamento_sku_redes', schema=None) as batch_op:
        batch_op.create_index('ix_map_medicamento_rede', ['medicamento_id', 'rede_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mapeamento_sku_redes_ean'), ['ean'], unique=False)
        batch_op.create_index(batch_op.f('ix_mapeamento_sku_redes_produto_cmed_ggrem'), ['produto_cmed_ggrem'], unique=False)

    op.create_table('historico_precos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mapeamento_id', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('preco_lista', sa.Float(), nullable=True),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.Column('praca', sa.String(length=40), nullable=False),
    sa.Column('fonte', sa.String(length=20), nullable=False),
    sa.Column('coletado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mapeamento_id'], ['mapeamento_sku_redes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historico_precos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historico_precos_coletado_em'), ['coletado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_historico_precos_mapeamento_id'), ['mapeamento_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_precos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historico_precos_mapeamento_id'))
        batch_op.drop_index(batch_op.f('ix_historico_precos_coletado_em'))

    op.drop_table('historico_precos')
    with op.batch_alter_table('mapeamento_sku_redes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mapeamento_sku_redes_produto_cmed_ggrem'))
        batch_op.drop_index(batch_op.f('ix_mapeamento_sku_redes_ean'))
        batch_op.drop_index('ix_map_medicamento_rede')

    op.drop_table('mapeamento_sku_redes')
    with op.batch_alter_table('produtos_cmed', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_cmed_registro'))
        batch_op.drop_index(batch_op.f('ix_produtos_cmed_produto'))
        batch_op.drop_index(batch_op.f('ix_produtos_cmed_medicamento_id'))
        batch_op.drop_index(batch_op.f('ix_produtos_cmed_ean3'))
        batch_op.drop_index(batch_op.f('ix_produtos_cmed_ean2'))
        batch_op.drop_index(batch_op.f('ix_produtos_cmed_ean1'))
        batch_op.drop_index(batch_op.f('ix_produtos_cmed_chave_apresentacao'))

    op.drop_table('produtos_cmed')
    op.drop_table('redes')
    op.drop_table('medicamentos')
    with op.batch_alter_table('execucoes_tarefas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execucoes_tarefas_tarefa'))

    op.drop_table('execucoes_tarefas')
    with op.batch_alter_table('cache_consultas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cache_consultas_expira_em'))

    op.drop_table('cache_consultas')
    # ### end Alembic commands ###
