"""rede somente online

Revision ID: d62f8f213dff
Revises: dc0fb9ff2382
Create Date: 2026-09-30 09:12:11.336432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd62f8f213dff'
down_revision: Union[str, None] = 'dc0fb9ff2382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('redes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('somente_online', sa.Boolean(), server_default=sa.false(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('redes', schema=None) as batch_op:
        batch_op.drop_column('somente_online')

    # ### end Alembic commands ###
