"""ofertas por sku

Revision ID: dc0fb9ff2382
Revises: bfd82a063a33
Create Date: 2026-09-29 23:11:40.279729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc0fb9ff2382'
down_revision: Union[str, None] = 'bfd82a063a33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ofertas_sku',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mapeamento_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('quantidade_minima', sa.Integer(), nullable=True),
    sa.Column('percentual', sa.Float(), nullable=True),
    sa.Column('preco_efetivo_unitario', sa.Float(), nullable=True),
    sa.Column('exige_cpf', sa.Boolean(), nullable=False),
    sa.Column('exige_cupom', sa.Boolean(), nullable=False),
    sa.Column('detalhes', sa.JSON(), nullable=False),
    sa.Column('coletado_em', sa.DateTime(), nullable=False),
    sa.Column('valido_ate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mapeamento_id'], ['mapeamento_sku_redes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ofertas_sku', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ofertas_sku_mapeamento_id'), ['mapeamento_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ofertas_sku', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ofertas_sku_mapeamento_id'))

    op.drop_table('ofertas_sku')
    # ### end Alembic commands ###
